# docker-compose.yml
version: "3.8"

services:
  localstack:
    container_name: "localstack-pro-main"
    # Use the 'localstack-pro' image for Pro features
    image: localstack/localstack-pro:latest
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # External services port range
    environment:
      # This line reads the Auth Token from your terminal's environment variable
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
      - DEBUG=${DEBUG:-0}
    volumes:
      - "localstack_volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  localstack_volume:
    name: "localstack_volume"